apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: madb-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: madb-api
          servicePort: 80
---          
apiVersion: v1
kind: Service
metadata:
  name: madb-api
  labels:
    name: madb-api
    madb-build-number: {{ .Values.image.tag | quote }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: madb-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: madb-api
  labels:
    name: madb-api
    madb-build-number: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: madb-api
  template:
    metadata:
      labels:
        app: madb-api 
        name: madb-api
        madb-build-number: {{ .Values.image.tag | quote }}
    spec:
      containers:
      - name: madb-api 
        image: raft/madb-api: {{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "java -Xmx{{- .Values.java.maxMemory }} \
                    -Dspring.datasource.password={{- .Values.madb.db.password }} \
                    {{- range $key, $value := .Values.java.properties }}
                    -D{{ $key }}={{ $value }} \
                    {{- end }}
                    -jar /app.jar" ]
        
        ports:
        - containerPort: 8080
        envFrom: 
          - configMapRef:
              name: madb-api-config
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: madb-api-config
  labels:
    name: madb-api-config
    madb-build-number: {{ .Values.image.tag | quote }}
data:
  {{- range $key, $value := .Values.env }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}  

