# CI (Continuous Integration) pipleine definition for Azure DevOps

trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - 'rest-api/*' 

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Docker build image
      inputs:
        command: build
        repository: raft/madb-api
        dockerfile: '$(Build.SourcesDirectory)/rest-api/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      displayName: Docker push image
      inputs:
        command: push
        containerRegistry: docker_hub_connection_raft
        repository: raft/madb-api
        tags: |
          $(tag)
          latest
    - publish: rest-api/kube/
      artifact: kube