ingress:
  host: api.madb.nl

# number of pod replicas
replicas: 1

# Docker image of Pod
image:
  tag: latest
  pullPolicy: IfNotPresent

# environment variables passed to Pod via ConfigMap 
env:
#  MD_USER: some value